Rtf - IFI assignment
S-Dafarra/Operational_Control_with_iCub pull request #1
Opened 2017-01-10 15:31 UTC by S-Dafarra

@francesco-romano @traversaro @pattacini

2017-01-10 17:27 UTC, traversaro commented
You can explicitly request a review in GitHub : 
https://help.github.com/articles/requesting-a-pull-request-review/

2017-01-10 17:33 UTC, traversaro requested changes

2017-01-10 17:33 UTC, traversaro commented on CMakeLists.txt
> +add_subdirectory(src/)
In general I always see add_subdirectory arguments without the path separator / . I think for consistency is good to omit it.

2017-01-10 17:33 UTC, traversaro commented on CMakeLists.txt
> +if(COMPILE_TEST)
There is a general purpose CMake option called BUILD_TESTING ( https://cmake.org/cmake/help/v3.1/module/CTest.html ).

2017-01-10 17:34 UTC, traversaro commented on CMakeLists.txt
> +if(COMPILE_TEST)
It is convenient to use that so that all CMake projects use the same option.

2020-12-14 13:15 UTC, pattacini commented
@S-Dafarra this is a super old PR that still appears on my personal dashboard.
Shall we close it?

2020-12-14 13:25 UTC, S-Dafarra commented
Still working on it 😂

2020-12-14 13:25 UTC, closed without merging